name: CI

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

# THIS WORKFLOW WAS ADDED BY MOORESLABAI

jobs:
  # This will automatically fetch the latest main branch from the parent we forked from
  # And it will reup the package with the latest changes to the main branch
  reup:
    name: Reup with fork main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # allow fetch-depth=0 so we can rebase/merge full history
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: 'recursive'

      - name: Configure Git user
        run: |
          git config user.name "Alex Navarro"
          git config user.email "v-alex@mooreslab.ai"

      - name: Add upstream remote
        # replace with your upstream repo
        run: |
          git remote add upstream https://github.com/openai/gpt-oss.git
          git remote -v

      - name: Fetch upstream/main
        run: git fetch upstream

      - name: Merge upstream into main
        continue-on-error: true
        run: |
          git checkout main
          git merge upstream/main --no-edit -X ours

      - name: Push merged changes
        continue-on-error: true
        run: git push origin main
